const vscode = require('vscode');

exports.specifiers = [

];

exports.metadata = [
    {
        label: 'Bitflags',
        doc: 'Indicates that this Enumeration can be used as flags by integer UPROPERTY variables that are set up with the "Bitmask" Metadata Specifier.'
    },
    {
        label: 'Experimental',
        doc: 'Labels this type as experimental and unsupported.'
    },
    {
        label: 'ScriptName',
        doc: 'The quoted string will be used as the name of this Enumeration in the Editor, rather than the default name generated by Unreal Header Tool.',
        insertText: new vscode.SnippetString('ScriptName="${1:Display Name}"')
    },
    {
        label: 'Tooltip',
        doc: 'Overrides the automatically generated tooltip from code comments.',
        insertText: new vscode.SnippetString('ToolTip="${1:Hand-written tooltip}"')
    }
];
