exports.specifiers = [
    {
        label: 'Atomic',
        doc: 'No autogenerated code will be created for this class; the header is only provided to parse metadata from.',
    },
    {
        label: 'BlueprintType',
        doc: 'Exposes this struct as a type that can be used for variables in Blueprints.',
    },
    {
        label: 'NoExport',
        doc: 'No autogenerated code will be created for this class; the header is only provided for parsing metadata.',
    },
];
