const vscode = require('vscode');

exports.specifiers = [
    {
        label: 'Atomic',
        doc: 'No autogenerated code will be created for this class; the header is only provided to parse metadata from.',
    },
    {
        label: 'BlueprintType',
        doc: 'Exposes this struct as a type that can be used for variables in Blueprints.',
    },
    {
        label: 'NoExport',
        doc: 'No autogenerated code will be created for this class; the header is only provided for parsing metadata.',
    },
];

exports.metadata = [
    {
        label: 'HasNativeBreak',
        insertText: new vscode.SnippetString('HasNativeBreak=${1:"Module.Class.Function"}'),
        doc: 'Indicates that this struct has a custom Break Struct node. The module, class, and function name must be provided.',
    },
    {
        label: 'HasNativeMake',
        insertText: new vscode.SnippetString('HasNativeMake=${1:"Module.Class.Function"}'),
        doc: 'Indicates that this struct has a custom Make Struct node. The module, class, and function name must be provided.',
    },
    {
        label: 'HiddenByDefault',
        doc: 'Pins in Make Struct and Break Struct nodes are hidden by default.',
    },
    {
        label: 'ShortToolTip',
        insertText: new vscode.SnippetString('ShortToolTip=${1:"Short tooltip"}'),
        doc: 'A short tooltip that is used in some contexts where the full tooltip might be overwhelming, such as the Parent Class Picker dialog.',
    },
    {
        label: 'ToolTip="Hand-written tooltip',
        doc: 'Overrides the automatically generated tooltip from code comments.',
    },
];
